# 50-hardcode-alsa.conf - PipeWire ALSA bare-metal routing.
# Copyright (C) 2026 Thiago C. Silva
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Bypass broken ALSA UCM profiles by forcing a direct, bare-metal ALSA sink.
context.objects = [
    {
	factory = "adapter"
        args = {
            "factory.name"     = "api.alsa.pcm.sink"
            "node.name"        = "alsa-hardcoded-analog"
            "node.description" = "ALC897 Bare Metal"
            "media.class"      = "Audio/Sink"
            "api.alsa.path"    = "hw:1,0"
        }
    }
]
